# Numpy Basics <hr style="border:2.5px solid#ff7f50"></hr>

Data Analyst: Bryx V. Agravante <br>
Department: Electrical Engineering

In [ ]:
%pip install numpy --upgrade

In [ ]:
%pip install scipy --upgrade

In [16]:
import numpy as np
from scipy import stats

# 1D Array

In [5]:
array_a = np.array([1,2,3])
array_a

array([1, 2, 3])

In [6]:
np.shape(array_a)

(3,)

In [7]:
array_b = np.array([4,5,6])
array_b

array([4, 5, 6])

# 2D Array

In [8]:
my_array = np.array([[1,2,3],[4,5,6]])
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
np.shape(my_array)

(2, 3)

In [10]:
t_array = my_array.T
t_array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [11]:
np.shape(t_array)

(3, 2)

# Measures of Central Tendecy

In [13]:
fruits = np.array([120,60,85,150,200])
fruits

array([120,  60,  85, 150, 200])

In [14]:
fruits_mean = np.mean(fruits)
fruits_mean

np.float64(123.0)

In [15]:
fruits_median = np.median(fruits)
fruits_median

np.float64(120.0)

In [18]:
fruits_mode = stats.mode(fruits)
fruits_mode

ModeResult(mode=np.int64(60), count=np.int64(1))

# Panther vs Jaguar

# Panther

In [19]:
panther = np.array([10.6,9.1,9.3,9.8,10.5,10.4,9.5,11,10.4,3,9.8])
panther

array([10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8])

In [20]:
mean_pan = np.mean(panther)
mean_pan

np.float64(9.399999999999999)

In [21]:
median_pan = np.median(panther)
median_pan

np.float64(9.8)

In [22]:
mode_pan = stats.mode(panther)
mode_pan

ModeResult(mode=np.float64(9.8), count=np.int64(2))

In [24]:
max_pan = np.max(panther)
min_pan = np.min(panther)

range_pan = max_pan - min_pan
range_pan

np.float64(8.0)

In [25]:
q1_pan = np.percentile(panther,25)
q1_pan

np.float64(9.4)

In [26]:
q3_pan = np.percentile(panther,75)
q3_pan

np.float64(10.45)

In [27]:
iqr_pan = q3_pan - q1_pan
iqr_pan

np.float64(1.049999999999999)

In [28]:
var_pan = np.var(panther)
var_pan

np.float64(4.418181818181818)

In [29]:
std_pan = np.std(panther)
std_pan

np.float64(2.101947149236112)

# Jaguar

In [30]:
jaguar = np.array([10.1,11,9.1,20,9.2,10.8,9.9,9.2,9.1,9.1])
jaguar

array([10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1])

In [31]:
mean_jag = np.mean(jaguar)
mean_jag

np.float64(10.75)

In [32]:
median_jag = np.median(jaguar)
median_jag

np.float64(9.55)

In [33]:
mode_jag = stats.mode(jaguar)
mode_jag

ModeResult(mode=np.float64(9.1), count=np.int64(3))

In [34]:
max_jag = np.max(jaguar)
min_jag = np.min(jaguar)

range_jag = max_jag - min_jag
range_jag

np.float64(10.9)

In [35]:
q1_jag = np.percentile(jaguar,25)
q1_jag

np.float64(9.125)

In [36]:
q3_jag = np.percentile(jaguar,75)
q3_jag

np.float64(10.625)

In [37]:
iqr_jag = q3_jag - q1_jag
iqr_jag

np.float64(1.5)

In [38]:
var_jag = np.var(jaguar)
var_jag

np.float64(9.974499999999999)

In [39]:
std_jag = np.std(jaguar)
std_jag

np.float64(3.1582431825304393)